# Generated by Django 5.2.1 on 2025-06-24 01:04

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='area_responsable',
            field=models.CharField(blank=True, help_text='Área del almacén bajo su responsabilidad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='certificaciones',
            field=models.TextField(blank=True, help_text='Certificaciones profesionales', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='comision_ventas',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión por ventas', max_digits=5),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Especialidad contable (ej: auditoría, costos, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='experiencia_anios',
            field=models.IntegerField(default=0, help_text='Años de experiencia en gestión de inventario'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('contador', 'Contador'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ventas_mes',
            field=models.IntegerField(default=0, help_text='Número de ventas realizadas este mes'),
        ),
    ]
