# Generated by Django 5.2.1 on 2025-06-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_activo_perfil_area_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nacimiento',
        ),
    ]
