# Generated by Django 4.2 on 2025-05-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productotienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
