# Generated by Django 4.2 on 2025-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock_actualizado',
            field=models.BooleanField(default=False),
        ),
    ]
