# Generated by Django 5.2.1 on 2025-05-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_pedido_stock_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='stock_actualizado',
            field=models.BooleanField(default=False, help_text='Indica si ya se descontó el stock al confirmar el pago'),
        ),
    ]
