# Generated by Django 5.2.1 on 2025-05-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_pedido_stock_actualizado'),
    ]

    operations = [
    ]
