# Generated by Django 5.2.1 on 2025-05-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_create_gestor_group'),
        ('productos', '0009_create_gestor_group'),
    ]

    operations = [
    ]
