# Generated by Django 5.2.1 on 2025-06-25 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_merge_20250523_0321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bodeguero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_bodeguero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='contador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_contador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_confirmacion_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_preparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], default='debito', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('tienda', 'Retiro en Tienda'), ('domicilio', 'Despacho a Domicilio')], default='tienda', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('preparando', 'Preparando'), ('listo_entrega', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='OrdenBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_vendedor', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('preparando', 'Preparando'), ('completada', 'Completada'), ('entregada', 'Entregada al Vendedor')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bodeguero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_bodega', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_bodega', to='productos.pedido')),
            ],
        ),
    ]
